name: redstar_hightech_backend
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  firebase_core: ^1.24.0
  firebase_auth: ^3.4.2

  cloud_firestore:
  charts_flutter:
  equatable:
  firebase_storage:
  image_picker:
  rflutter_alert:
  path_provider:
  url_launcher: ^6.0.0-nullsafety
  get: 
  image_cropper:
  flutter_image_compress:
  drawerbehavior: 
  animated_text_kit: 
  font_awesome_flutter: 
  shared_preferences: 
  settings_ui: 
  hive: 
  hive_flutter:
  flutter_local_notifications: 
  flutter_native_timezone:  
  flutter_svg:
  velocity_x:  
  google_sign_in:
  device_info_plus:
  package_info_plus:
  safe_url_check:
  confirm_dialog:

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/
 #   - assets/images/bg.png
 #   - assets/images/empty.png
 #   - assets/images/
