name: redstar_hightech_backend
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  cloud_firestore:
  charts_flutter:
  equatable:
  firebase_core:
  firebase_storage:
  image_picker:  
  responsive_table: ^0.2.0+2
  rflutter_alert: ^1.0.3
  path_provider:


dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/bg.png
    - assets/images/empty.png
    - assets/images/


