name: redstar_hightech_backend
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  cloud_firestore:
  charts_flutter:
  equatable:
  firebase_core:
  firebase_storage:
  image_picker:  
  responsive_table: ^0.2.0+2
  rflutter_alert: ^1.0.3
  path_provider:

  googleapis: ^7.0.0
  googleapis_auth: ^1.3.0
  flutter_secure_storage: ^5.0.2
  url_launcher: ^6.0.0-nullsafety

  image_cropper:
  flutter_image_compress:
  drawerbehavior: 
  animated_text_kit: 
  font_awesome_flutter: 
  shared_preferences: 
  settings_ui: 
  hive: 
  hive_flutter:
  flutter_local_notifications: 
  flutter_native_timezone: 



dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
 #   - assets/images/bg.png
 #   - assets/images/empty.png
 #   - assets/images/


